"""Gebäudetyp → Anzeigename Mapping.

Ausgelagert aus strategy.py um zirkuläre Importe zu vermeiden.
(strategy.py importiert task_state, task_state brauchte building_display_name)
"""
from __future__ import annotations

# Vollständige Liste aller bekannten Live-Gebäude (Stand 2026-04, /api/city/).
# Gebäude die hier NICHT stehen, lösen eine Telegram-Meldung aus.
BUILDING_NAMES: dict[str, str] = {
    # ── Wohngebäude ─────────────────────────────────────────────────────────
    "tent":                  "Zelt",
    "house_small":           "Kleines Wohnhaus",
    "house_medium":          "Mittleres Wohnhaus",
    "house_large":           "Großes Wohnhaus",
    "pop_center":            "Bevölkerungszentrum",
    "settlement_complex":    "Siedlungskomplex",
    "villa_complex":         "Villenkomplex",
    "clone_center":          "Klonzentrum",
    "orbital_habitat":       "Orbitales Habitat",
    "asteroid_housing":      "Asteroiden-Wohnanlage",
    "asteroid_platform":     "Asteroiden-Wohnplatf.",
    "gasgiant_housing":      "Gasgiganten-Wohnanlage",
    # ── Soziales / Zufriedenheit ────────────────────────────────────────────
    "outhouse":              "Plumpsklo",
    "park":                  "Park",
    "flower_beds":           "Blumenrabatte",
    "asylum":                "Irrenanstalt",
    "scout_camp":            "Pfadfindercamp",
    "tavern":                "Taverne",
    "beauty_salon":          "Schönheitssalon",
    "teen_disco":            "Teen-Disco",
    "pizza_small":           "24h Pizza",
    "pizza_large":           "5-Sterne Pizzalokal",
    "waffle_stand":          "Waffelstand",
    "statue":                "Statue",
    "spoon_monument":        "Löffelmonument",
    # ── Energie ─────────────────────────────────────────────────────────────
    "solar_panels":          "Solarplatten",
    "solar_plant":           "Solarkraftwerk",
    "combustion_plant":      "Verbrennungskraftwerk",
    "district_heat":         "Fernwärmekraftwerk",
    "fuel_cell":             "Brennstoffzelle",
    "nuclear_plant":         "Atomkraftwerk",
    "fusion_plant":          "Fusionskraftwerk",
    "orbital_solar":         "Orbitales Solarkraftwerk",
    # ── Produktion ──────────────────────────────────────────────────────────
    "iron_mine_small":       "Kleine Eisenmine",
    "iron_mine_large":       "Große Eisenmine",
    "iron_complex":          "Eisenkomplex",
    "asteroid_mine":         "Asteroidenmine",
    "moon_mine":             "Mondbergwerk",
    "steel_works_small":     "Kleines Stahlwerk",
    "steel_works_large":     "Großes Stahlwerk",
    "steel_complex":         "Kleiner Stahlkomplex",
    "chem_factory_small":    "Kleine Chemiefabrik",
    "chem_factory_large":    "Große Chemiefabrik",
    "chem_complex":          "Chemiekomplex",
    "tauchsieder":           "Tauchsieder MK IV",
    "water_plant":           "Wasserwerk",
    "distillery":            "Destillationsanlage",
    "ice_crusher_design":    "Eiscrusher Design",
    "ice_crusher_large":     "Großer Eiscrusher",
    "crusher_v3a":           "Crusher V3A",
    "crusher_v3b":           "Crusher V3B",
    "vv4a_works":            "VV4A-Werk",
    "vv4a_works_large":      "Großes VV4A-Werk",
    "biosphere":             "Biosphäre",
    # ── Forschung ───────────────────────────────────────────────────────────
    "research_lab":          "Forschungslabor",
    "research_complex":      "Forschungskomplex",
    "university":            "Universität",
    "library":               "Intergalaktische Bibliothek",
    "supercomputer":         "Supercomputer",
    "quantum_computer":      "Quantencomputer",
    "orbital_lab":           "Orbitales Labor",
    "underground_lab":       "Unterirdisches Forschkomplex",
    "volcano_lab":           "Vulkanlabor",
    # ── Lager (regulär) ─────────────────────────────────────────────────────
    "iron_storage_small":    "Eisenlager",
    "iron_storage_large":    "Großes Eisenlager",
    "steel_storage_small":   "Stahllager",
    "steel_storage_large":   "Großes Stahllager",
    "chem_storage_small":    "Chemielager",
    "chem_storage_lg":       "Großes Chemielager",
    "ice_water_storage":     "Eis-/Wasserlager",
    "energy_storage":        "Energielager",
    "energy_storage_lg":     "Großes Energielager",
    "vv4a_storage_small":    "VV4A-Lager",
    "vv4a_storage_large":    "Großes VV4A-Lager",
    # ── Lager (Bunker) ───────────────────────────────────────────────────────
    "iron_bunker":           "Eisenbunker",
    "steel_bunker":          "Stahlbunker",
    "chem_bunker":           "Chemiebunker",
    "ice_water_bunker":      "Eis-/Wasserbunker",
    "energy_bunker":         "Energiebunker",
    "vv4a_bunker":           "VV4A-Bunker",
    "pop_bunker":            "Bevölkerungsbunker",
    # ── Infrastruktur ───────────────────────────────────────────────────────
    "city_center":           "Stadtzentrum",
    "headquarters":          "Hauptquartier",
    "colonize_center":       "Kolonisierungszentrum",
    "comm_small":            "Kleine Kommunikationsanlage",
    "comm_large":            "Große Kommunikationsanlage",
    "recycler":              "Recycler",
    "orbital_recycler":      "Orbitaler Recycler",
    "robotics":              "Roboterzentrale",
    "structural":            "Strukturbauprogramm",
    "terraforming":          "Terraforming",
    "orbital_lift":          "Orbitaler Aufzug",
    # ── Wirtschaft / Economy ────────────────────────────────────────────────
    "bank":                  "Bank",
    "trade_company":         "Handelsgesellschaft",
    "commerce_temple":       "Kommerztempel",
    "sirius_corp":           "Sirius Corporation",
    "imperial_tax":          "Imperiale Steuerbehörde",
    "gold_mine":             "Goldmine",
    "spaceport":             "Planetarer Raumhafen",
    "bureaucracy":           "Verwaltungskomplex",
    # ── Militär ─────────────────────────────────────────────────────────────
    "telescope":             "Orbitales Teleskop",
    "long_telescope":        "Lang-Teleskop",
    "deep_telescope":        "Tiefenteleskop",
    "observatory":           "Sternenwarte",
    "base_scanner":          "Planetarer Basisscanner",
    "fleet_scanner":         "Flottenscanner",
    "orbital_scanner":       "Orbitaler Galaxiescanner",
    "fog_machine":           "Nebelmaschine",
    "fleet_control":         "Flottenkontrollzentrum",
    "km_defence_fab":        "K&M Abwehr Fabrik",
    # ── Verteidigung ────────────────────────────────────────────────────────
    "defence_position":      "Verteidigungsstellung",
    "kb_alpha":              "Kampfbasis Alpha",
    "shield_alpha":          "Planetarschild Alpha",
    "shield_beta":           "Planetarschild Beta",
    "mass_driver":           "Massentreiber",
    "moon_defence":          "Mondverteidigung",
    "combat_control":        "Kampfbasiskontrolle",
    "planetary_armor":       "Panzer-Update Planetar",
    "orbital_armor":         "Panzer-Update Orbital",
    "base_def_orbital":      "Orb. Basenverteidigung",
    "orb_def_control":       "Orb. Verteidigungskontrolle",
    "orb_def_coord":         "Orb. Verteidigungskoordinator",
    # ── Werften ─────────────────────────────────────────────────────────────
    "launch_pad":            "Startrampe",
    "shipyard_plan_small":   "Kleine Planetarwerft",
    "shipyard_plan_mid":     "Mittlere Planetarwerft",
    "shipyard_large":        "Große Werft",
    "shipyard_orb_small":    "Kleine Orbitalwerft",
    "shipyard_orb_mid":      "Mittlere Orbitalwerft",
    "shipyard_dn":           "DN-Werft",
    "shipyard_complex":      "Orbitaler Werftkomplex",
    # ── Shop-Pakete (nicht baubar, nur zur Erkennung) ───────────────────────
    "kit_iron":              "Eisen-Hilfspaket",
    "kit_steel":             "Stahl-Hilfspaket",
    "kit_chem":              "Chemie-Hilfspaket",
    "kit_ice":               "Eis-Hilfspaket",
    "kit_water":             "Wasser-Paket",
    "kit_energy":            "Energie-Brennstäbe",
    "kit_lurch":             "Lurch-Paket",
    "kit_scout":             "Scout-Paket",
    "kit_systrans":          "Systrans-Paket",
}


def building_display_name(btype: str, fallback: str = "") -> str:
    """Gibt den deutschen Anzeigenamen eines Gebäudetyps zurück."""
    return BUILDING_NAMES.get(btype, fallback or btype)
